"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ActivityTypedDict(TypedDict):
    title: NotRequired[str]
    r"""A user-friendly title for this activity"""
    type: NotRequired[str]
    r"""The type of activity"""
    cancellable: NotRequired[bool]
    r"""Indicates whether this activity can be cancelled"""
    context: NotRequired[Dict[str, Any]]
    r"""An object with additional values"""
    progress: NotRequired[float]
    r"""A progress percentage.  A value of -1 means the progress is indeterminate"""
    response: NotRequired[Dict[str, Any]]
    r"""An object with the response to the async opperation"""
    subtitle: NotRequired[str]
    r"""A user-friendly sub-title for this activity"""
    user_id: NotRequired[int]
    r"""The user this activity belongs to"""
    uuid: NotRequired[str]
    r"""The ID of the activity"""


class Activity(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    title: Optional[str] = None
    r"""A user-friendly title for this activity"""

    type: Optional[str] = None
    r"""The type of activity"""

    cancellable: Optional[bool] = None
    r"""Indicates whether this activity can be cancelled"""

    context: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="Context")] = None
    r"""An object with additional values"""

    progress: Optional[float] = None
    r"""A progress percentage.  A value of -1 means the progress is indeterminate"""

    response: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="Response")] = (
        None
    )
    r"""An object with the response to the async opperation"""

    subtitle: Optional[str] = None
    r"""A user-friendly sub-title for this activity"""

    user_id: Annotated[Optional[int], pydantic.Field(alias="userID")] = None
    r"""The user this activity belongs to"""

    uuid: Optional[str] = None
    r"""The ID of the activity"""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "type",
                "cancellable",
                "Context",
                "progress",
                "Response",
                "subtitle",
                "userID",
                "uuid",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


try:
    Activity.model_rebuild()
except NameError:
    pass
