"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AddedQueueItemTypedDict(TypedDict):
    id: NotRequired[int]
    r"""The queue item id that was added or the existing one if an item already exists in this queue with the same parameters"""
    key: NotRequired[str]
    r"""The key added to the queue"""


class AddedQueueItem(BaseModel):
    id: Optional[int] = None
    r"""The queue item id that was added or the existing one if an item already exists in this queue with the same parameters"""

    key: Optional[str] = None
    r"""The key added to the queue"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
