"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from typing import Union
from typing_extensions import TypeAliasType


class AllowSync3(str, Enum):
    ZERO = "0"
    ONE = "1"


AllowSyncTypedDict = TypeAliasType("AllowSyncTypedDict", Union[bool, AllowSync3])


AllowSync = TypeAliasType("AllowSync", Union[bool, AllowSync3])
