"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AuthTokenResponseTypedDict(TypedDict):
    auth_token: NotRequired[str]
    r"""The Plex authentication token"""
    client_identifier: NotRequired[str]
    jwt: NotRequired[str]
    r"""JWT token for device authentication"""


class AuthTokenResponse(BaseModel):
    auth_token: Annotated[Optional[str], pydantic.Field(alias="authToken")] = None
    r"""The Plex authentication token"""

    client_identifier: Annotated[
        Optional[str], pydantic.Field(alias="clientIdentifier")
    ] = None

    jwt: Optional[str] = None
    r"""JWT token for device authentication"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["authToken", "clientIdentifier", "jwt"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AuthTokenResponse.model_rebuild()
except NameError:
    pass
