"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ChannelMappingTypedDict(TypedDict):
    channel_key: NotRequired[str]
    device_identifier: NotRequired[str]
    enabled: NotRequired[str]
    lineup_identifier: NotRequired[str]


class ChannelMapping(BaseModel):
    channel_key: Annotated[Optional[str], pydantic.Field(alias="channelKey")] = None

    device_identifier: Annotated[
        Optional[str], pydantic.Field(alias="deviceIdentifier")
    ] = None

    enabled: Optional[str] = None

    lineup_identifier: Annotated[
        Optional[str], pydantic.Field(alias="lineupIdentifier")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["channelKey", "deviceIdentifier", "enabled", "lineupIdentifier"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ChannelMapping.model_rebuild()
except NameError:
    pass
