"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ChannelTypedDict(TypedDict):
    title: NotRequired[str]
    call_sign: NotRequired[str]
    channel_vcn: NotRequired[str]
    drm: NotRequired[bool]
    r"""Whether the channel requires DRM."""
    favorite: NotRequired[bool]
    r"""Whether the channel is marked as a favorite."""
    hd: NotRequired[bool]
    identifier: NotRequired[str]
    key: NotRequired[str]
    language: NotRequired[str]
    signal_quality: NotRequired[int]
    r"""Signal quality percentage (0-100)."""
    signal_strength: NotRequired[int]
    r"""Signal strength percentage (0-100)."""
    thumb: NotRequired[str]


class Channel(BaseModel):
    title: Optional[str] = None

    call_sign: Annotated[Optional[str], pydantic.Field(alias="callSign")] = None

    channel_vcn: Annotated[Optional[str], pydantic.Field(alias="channelVcn")] = None

    drm: Optional[bool] = None
    r"""Whether the channel requires DRM."""

    favorite: Optional[bool] = None
    r"""Whether the channel is marked as a favorite."""

    hd: Optional[bool] = None

    identifier: Optional[str] = None

    key: Optional[str] = None

    language: Optional[str] = None

    signal_quality: Annotated[Optional[int], pydantic.Field(alias="signalQuality")] = (
        None
    )
    r"""Signal quality percentage (0-100)."""

    signal_strength: Annotated[
        Optional[int], pydantic.Field(alias="signalStrength")
    ] = None
    r"""Signal strength percentage (0-100)."""

    thumb: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "callSign",
                "channelVcn",
                "drm",
                "favorite",
                "hd",
                "identifier",
                "key",
                "language",
                "signalQuality",
                "signalStrength",
                "thumb",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Channel.model_rebuild()
except NameError:
    pass
