"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ChannelTypedDict(TypedDict):
    title: NotRequired[str]
    call_sign: NotRequired[str]
    channel_vcn: NotRequired[str]
    hd: NotRequired[bool]
    identifier: NotRequired[str]
    key: NotRequired[str]
    language: NotRequired[str]
    thumb: NotRequired[str]


class Channel(BaseModel):
    title: Optional[str] = None

    call_sign: Annotated[Optional[str], pydantic.Field(alias="callSign")] = None

    channel_vcn: Annotated[Optional[str], pydantic.Field(alias="channelVcn")] = None

    hd: Optional[bool] = None

    identifier: Optional[str] = None

    key: Optional[str] = None

    language: Optional[str] = None

    thumb: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "callSign",
                "channelVcn",
                "hd",
                "identifier",
                "key",
                "language",
                "thumb",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Channel.model_rebuild()
except NameError:
    pass
