"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CollectionMode(str, Enum):
    r"""Display mode for the collection."""

    DEFAULT = "default"
    HIDE_ITEMS = "hideItems"
    SHOW_ITEMS = "showItems"


class CollectionTypedDict(TypedDict):
    r"""A collection of related media items."""

    art_blur_hash: NotRequired[str]
    r"""Blur hash for collection art."""
    collection_filter_based_on_user: NotRequired[bool]
    r"""Whether the smart collection filter is based on the current user."""
    collection_mode: NotRequired[CollectionMode]
    r"""Display mode for the collection."""
    collection_published: NotRequired[bool]
    r"""Whether the collection is published to Plex Discover."""
    collection_sort: NotRequired[str]
    r"""Sort order for items in the collection."""
    last_rated_at: NotRequired[int]
    r"""Timestamp of the last user rating."""
    thumb_blur_hash: NotRequired[str]
    r"""Blur hash for collection thumbnail."""
    user_rating: NotRequired[float]
    r"""User star rating (0-10)."""


class Collection(BaseModel):
    r"""A collection of related media items."""

    art_blur_hash: Annotated[Optional[str], pydantic.Field(alias="artBlurHash")] = None
    r"""Blur hash for collection art."""

    collection_filter_based_on_user: Annotated[
        Optional[bool], pydantic.Field(alias="collectionFilterBasedOnUser")
    ] = None
    r"""Whether the smart collection filter is based on the current user."""

    collection_mode: Annotated[
        Optional[CollectionMode], pydantic.Field(alias="collectionMode")
    ] = None
    r"""Display mode for the collection."""

    collection_published: Annotated[
        Optional[bool], pydantic.Field(alias="collectionPublished")
    ] = None
    r"""Whether the collection is published to Plex Discover."""

    collection_sort: Annotated[
        Optional[str], pydantic.Field(alias="collectionSort")
    ] = None
    r"""Sort order for items in the collection."""

    last_rated_at: Annotated[Optional[int], pydantic.Field(alias="lastRatedAt")] = None
    r"""Timestamp of the last user rating."""

    thumb_blur_hash: Annotated[Optional[str], pydantic.Field(alias="thumbBlurHash")] = (
        None
    )
    r"""Blur hash for collection thumbnail."""

    user_rating: Annotated[Optional[float], pydantic.Field(alias="userRating")] = None
    r"""User star rating (0-10)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "artBlurHash",
                "collectionFilterBasedOnUser",
                "collectionMode",
                "collectionPublished",
                "collectionSort",
                "lastRatedAt",
                "thumbBlurHash",
                "userRating",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Collection.model_rebuild()
except NameError:
    pass
