"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DecisionResultTypedDict(TypedDict):
    available_bandwidth: NotRequired[int]
    r"""The maximum bitrate set when item was added"""
    direct_play_decision_code: NotRequired[int]
    direct_play_decision_text: NotRequired[str]
    general_decision_code: NotRequired[int]
    general_decision_text: NotRequired[str]
    mde_decision_code: NotRequired[int]
    r"""The code indicating the status of evaluation of playback when client indicates `hasMDE=1`"""
    mde_decision_text: NotRequired[str]
    r"""Descriptive text for the above code"""
    transcode_decision_code: NotRequired[int]
    transcode_decision_text: NotRequired[str]


class DecisionResult(BaseModel):
    available_bandwidth: Annotated[
        Optional[int], pydantic.Field(alias="availableBandwidth")
    ] = None
    r"""The maximum bitrate set when item was added"""

    direct_play_decision_code: Annotated[
        Optional[int], pydantic.Field(alias="directPlayDecisionCode")
    ] = None

    direct_play_decision_text: Annotated[
        Optional[str], pydantic.Field(alias="directPlayDecisionText")
    ] = None

    general_decision_code: Annotated[
        Optional[int], pydantic.Field(alias="generalDecisionCode")
    ] = None

    general_decision_text: Annotated[
        Optional[str], pydantic.Field(alias="generalDecisionText")
    ] = None

    mde_decision_code: Annotated[
        Optional[int], pydantic.Field(alias="mdeDecisionCode")
    ] = None
    r"""The code indicating the status of evaluation of playback when client indicates `hasMDE=1`"""

    mde_decision_text: Annotated[
        Optional[str], pydantic.Field(alias="mdeDecisionText")
    ] = None
    r"""Descriptive text for the above code"""

    transcode_decision_code: Annotated[
        Optional[int], pydantic.Field(alias="transcodeDecisionCode")
    ] = None

    transcode_decision_text: Annotated[
        Optional[str], pydantic.Field(alias="transcodeDecisionText")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "availableBandwidth",
                "directPlayDecisionCode",
                "directPlayDecisionText",
                "generalDecisionCode",
                "generalDecisionText",
                "mdeDecisionCode",
                "mdeDecisionText",
                "transcodeDecisionCode",
                "transcodeDecisionText",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DecisionResult.model_rebuild()
except NameError:
    pass
