"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .channelmapping import ChannelMapping, ChannelMappingTypedDict
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeviceTypedDict(TypedDict):
    channel_mapping: NotRequired[List[ChannelMappingTypedDict]]
    key: NotRequired[str]
    last_seen_at: NotRequired[int]
    make: NotRequired[str]
    model: NotRequired[str]
    model_number: NotRequired[str]
    protocol: NotRequired[str]
    sources: NotRequired[str]
    state: NotRequired[str]
    status: NotRequired[str]
    tuners: NotRequired[str]
    uri: NotRequired[str]
    uuid: NotRequired[str]


class Device(BaseModel):
    channel_mapping: Annotated[
        Optional[List[ChannelMapping]], pydantic.Field(alias="ChannelMapping")
    ] = None

    key: Optional[str] = None

    last_seen_at: Annotated[Optional[int], pydantic.Field(alias="lastSeenAt")] = None

    make: Optional[str] = None

    model: Optional[str] = None

    model_number: Annotated[Optional[str], pydantic.Field(alias="modelNumber")] = None

    protocol: Optional[str] = None

    sources: Optional[str] = None

    state: Optional[str] = None

    status: Optional[str] = None

    tuners: Optional[str] = None

    uri: Optional[str] = None

    uuid: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "ChannelMapping",
                "key",
                "lastSeenAt",
                "make",
                "model",
                "modelNumber",
                "protocol",
                "sources",
                "state",
                "status",
                "tuners",
                "uri",
                "uuid",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Device.model_rebuild()
except NameError:
    pass
