"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeviceChannelTypedDict(TypedDict):
    drm: NotRequired[bool]
    r"""Indicates the channel is DRMed and thus may not be playable"""
    favorite: NotRequired[bool]
    hd: NotRequired[bool]
    identifier: NotRequired[str]
    key: NotRequired[str]
    name: NotRequired[str]
    signal_quality: NotRequired[int]
    signal_strength: NotRequired[int]


class DeviceChannel(BaseModel):
    drm: Optional[bool] = None
    r"""Indicates the channel is DRMed and thus may not be playable"""

    favorite: Optional[bool] = None

    hd: Optional[bool] = None

    identifier: Optional[str] = None

    key: Optional[str] = None

    name: Optional[str] = None

    signal_quality: Annotated[Optional[int], pydantic.Field(alias="signalQuality")] = (
        None
    )

    signal_strength: Annotated[
        Optional[int], pydantic.Field(alias="signalStrength")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "drm",
                "favorite",
                "hd",
                "identifier",
                "key",
                "name",
                "signalQuality",
                "signalStrength",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DeviceChannel.model_rebuild()
except NameError:
    pass
