"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Status(str, Enum):
    r"""The state of this queue
    - deciding: At least one item is still being decided
    - waiting: At least one item is waiting for transcode and none are currently transcoding
    - processing: At least one item is being transcoded
    - done: All items are available (or potentially expired)
    - error: At least one item has encountered an error
    """

    DECIDING = "deciding"
    WAITING = "waiting"
    PROCESSING = "processing"
    DONE = "done"
    ERROR = "error"


class DownloadQueueTypedDict(TypedDict):
    id: NotRequired[int]
    item_count: NotRequired[int]
    status: NotRequired[Status]
    r"""The state of this queue
    - deciding: At least one item is still being decided
    - waiting: At least one item is waiting for transcode and none are currently transcoding
    - processing: At least one item is being transcoded
    - done: All items are available (or potentially expired)
    - error: At least one item has encountered an error
    """


class DownloadQueue(BaseModel):
    id: Optional[int] = None

    item_count: Annotated[Optional[int], pydantic.Field(alias="itemCount")] = None

    status: Optional[Status] = None
    r"""The state of this queue
    - deciding: At least one item is still being decided
    - waiting: At least one item is waiting for transcode and none are currently transcoding
    - processing: At least one item is being transcoded
    - done: All items are available (or potentially expired)
    - error: At least one item has encountered an error
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "itemCount", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DownloadQueue.model_rebuild()
except NameError:
    pass
