"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .device import Device, DeviceTypedDict
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DvrTypedDict(TypedDict):
    device: NotRequired[List[DeviceTypedDict]]
    key: NotRequired[str]
    language: NotRequired[str]
    lineup: NotRequired[str]
    uuid: NotRequired[str]


class Dvr(BaseModel):
    device: Annotated[Optional[List[Device]], pydantic.Field(alias="Device")] = None

    key: Optional[str] = None

    language: Optional[str] = None

    lineup: Optional[str] = None

    uuid: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Device", "key", "language", "lineup", "uuid"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Dvr.model_rebuild()
except NameError:
    pass
