"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class GeoIPResponseTypedDict(TypedDict):
    city: NotRequired[str]
    coordinates: NotRequired[str]
    country: NotRequired[str]
    country_code: NotRequired[str]
    subdivisions: NotRequired[str]
    timezone: NotRequired[str]


class GeoIPResponse(BaseModel):
    city: Optional[str] = None

    coordinates: Optional[str] = None

    country: Optional[str] = None

    country_code: Optional[str] = None

    subdivisions: Optional[str] = None

    timezone: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "city",
                "coordinates",
                "country",
                "country_code",
                "subdivisions",
                "timezone",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
