"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class JwkTypedDict(TypedDict):
    r"""JSON Web Key for device authentication"""

    crv: NotRequired[str]
    kid: NotRequired[str]
    kty: NotRequired[str]
    x: NotRequired[str]


class Jwk(BaseModel):
    r"""JSON Web Key for device authentication"""

    crv: Optional[str] = None

    kid: Optional[str] = None

    kty: Optional[str] = None

    x: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["crv", "kid", "kty", "x"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class JWKRegistrationRequestTypedDict(TypedDict):
    jwk: NotRequired[JwkTypedDict]
    r"""JSON Web Key for device authentication"""
    strong: NotRequired[bool]
    r"""Request strong authentication"""


class JWKRegistrationRequest(BaseModel):
    jwk: Optional[Jwk] = None
    r"""JSON Web Key for device authentication"""

    strong: Optional[bool] = False
    r"""Request strong authentication"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["jwk", "strong"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
