"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .mediatypestring import MediaTypeString
from enum import Enum
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class AllowSync2(str, Enum):
    ZERO = "0"
    ONE = "1"


LibrarySectionAllowSyncTypedDict = TypeAliasType(
    "LibrarySectionAllowSyncTypedDict", Union[bool, AllowSync2]
)


LibrarySectionAllowSync = TypeAliasType(
    "LibrarySectionAllowSync", Union[bool, AllowSync2]
)


class LibrarySectionLocationTypedDict(TypedDict):
    r"""Represents a top-level location on disk where media in this library section is stored"""

    id: NotRequired[int]
    path: NotRequired[Any]
    r"""The path of where this directory exists on disk"""


class LibrarySectionLocation(BaseModel):
    r"""Represents a top-level location on disk where media in this library section is stored"""

    id: Optional[int] = None

    path: Optional[Any] = None
    r"""The path of where this directory exists on disk"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "path"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class LibrarySectionTypedDict(TypedDict):
    type: MediaTypeString
    r"""The type of media content in the Plex library. This can represent videos, music, or photos.

    """
    language: str
    uuid: str
    r"""The universally unique identifier for the library."""
    title: NotRequired[str]
    r"""The title of the library"""
    agent: NotRequired[str]
    allow_sync: NotRequired[LibrarySectionAllowSyncTypedDict]
    art: NotRequired[str]
    composite: NotRequired[str]
    content: NotRequired[bool]
    content_changed_at: NotRequired[int]
    created_at: NotRequired[int]
    directory: NotRequired[bool]
    filters: NotRequired[bool]
    r"""Indicates whether this section has filtering capabilities"""
    hidden: NotRequired[bool]
    key: NotRequired[str]
    location: NotRequired[List[LibrarySectionLocationTypedDict]]
    refreshing: NotRequired[bool]
    r"""Indicates whether this library section is currently scanning"""
    scanned_at: NotRequired[int]
    scanner: NotRequired[str]
    thumb: NotRequired[str]
    updated_at: NotRequired[int]


class LibrarySection(BaseModel):
    type: MediaTypeString
    r"""The type of media content in the Plex library. This can represent videos, music, or photos.

    """

    language: str

    uuid: str
    r"""The universally unique identifier for the library."""

    title: Optional[str] = None
    r"""The title of the library"""

    agent: Optional[str] = None

    allow_sync: Annotated[
        Optional[LibrarySectionAllowSync], pydantic.Field(alias="allowSync")
    ] = None

    art: Optional[str] = None

    composite: Optional[str] = None

    content: Optional[bool] = None

    content_changed_at: Annotated[
        Optional[int], pydantic.Field(alias="contentChangedAt")
    ] = None

    created_at: Annotated[Optional[int], pydantic.Field(alias="createdAt")] = None

    directory: Optional[bool] = None

    filters: Optional[bool] = None
    r"""Indicates whether this section has filtering capabilities"""

    hidden: Optional[bool] = None

    key: Optional[str] = None

    location: Annotated[
        Optional[List[LibrarySectionLocation]], pydantic.Field(alias="Location")
    ] = None

    refreshing: Optional[bool] = None
    r"""Indicates whether this library section is currently scanning"""

    scanned_at: Annotated[Optional[int], pydantic.Field(alias="scannedAt")] = None

    scanner: Optional[str] = None

    thumb: Optional[str] = None

    updated_at: Annotated[Optional[int], pydantic.Field(alias="updatedAt")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "agent",
                "allowSync",
                "art",
                "composite",
                "content",
                "contentChangedAt",
                "createdAt",
                "directory",
                "filters",
                "hidden",
                "key",
                "Location",
                "refreshing",
                "scannedAt",
                "scanner",
                "thumb",
                "updatedAt",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    LibrarySection.model_rebuild()
except NameError:
    pass
