"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class HomeVisibility(str, Enum):
    r"""Whether this hub is visible on the home screen
    - all: Visible to all users
    - none: Visible to no users
    - admin: Visible to only admin users
    - shared: Visible to shared users
    """

    ALL = "all"
    NONE = "none"
    ADMIN = "admin"
    SHARED = "shared"


class RecommendationsVisibility(str, Enum):
    r"""The visibility of this hub in recommendations:
    - all: Visible to all users
    - none: Visible to no users
    - admin: Visible to only admin users
    - shared: Visible to shared users
    """

    ALL = "all"
    NONE = "none"
    ADMIN = "admin"
    SHARED = "shared"


class ManagedHubTypedDict(TypedDict):
    title: NotRequired[str]
    r"""The title of this hub"""
    home_visibility: NotRequired[HomeVisibility]
    r"""Whether this hub is visible on the home screen
    - all: Visible to all users
    - none: Visible to no users
    - admin: Visible to only admin users
    - shared: Visible to shared users
    """
    identifier: NotRequired[str]
    r"""The identifier for this hub"""
    promoted_to_own_home: NotRequired[bool]
    r"""Whether this hub is visible to admin user home"""
    promoted_to_recommended: NotRequired[bool]
    r"""Whether this hub is promoted to all for recommendations"""
    promoted_to_shared_home: NotRequired[bool]
    r"""Whether this hub is visible to shared user's home"""
    recommendations_visibility: NotRequired[RecommendationsVisibility]
    r"""The visibility of this hub in recommendations:
    - all: Visible to all users
    - none: Visible to no users
    - admin: Visible to only admin users
    - shared: Visible to shared users
    """


class ManagedHub(BaseModel):
    title: Optional[str] = None
    r"""The title of this hub"""

    home_visibility: Annotated[
        Optional[HomeVisibility], pydantic.Field(alias="homeVisibility")
    ] = None
    r"""Whether this hub is visible on the home screen
    - all: Visible to all users
    - none: Visible to no users
    - admin: Visible to only admin users
    - shared: Visible to shared users
    """

    identifier: Optional[str] = None
    r"""The identifier for this hub"""

    promoted_to_own_home: Annotated[
        Optional[bool], pydantic.Field(alias="promotedToOwnHome")
    ] = None
    r"""Whether this hub is visible to admin user home"""

    promoted_to_recommended: Annotated[
        Optional[bool], pydantic.Field(alias="promotedToRecommended")
    ] = None
    r"""Whether this hub is promoted to all for recommendations"""

    promoted_to_shared_home: Annotated[
        Optional[bool], pydantic.Field(alias="promotedToSharedHome")
    ] = None
    r"""Whether this hub is visible to shared user's home"""

    recommendations_visibility: Annotated[
        Optional[RecommendationsVisibility],
        pydantic.Field(alias="recommendationsVisibility"),
    ] = None
    r"""The visibility of this hub in recommendations:
    - all: Visible to all users
    - none: Visible to no users
    - admin: Visible to only admin users
    - shared: Visible to shared users
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "homeVisibility",
                "identifier",
                "promotedToOwnHome",
                "promotedToRecommended",
                "promotedToSharedHome",
                "recommendationsVisibility",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ManagedHub.model_rebuild()
except NameError:
    pass
