"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MediaContainerWithPlayQueueTypedDict(TypedDict):
    r"""A media container representing a play queue."""

    identifier: NotRequired[str]
    offset: NotRequired[int]
    r"""The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header."""
    size: NotRequired[int]
    total_size: NotRequired[int]
    r"""The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header."""
    play_queue_id: NotRequired[int]
    play_queue_last_added_item_id: NotRequired[int]
    play_queue_selected_item_id: NotRequired[int]
    play_queue_selected_item_offset: NotRequired[int]
    play_queue_selected_metadata_item_id: NotRequired[int]
    play_queue_shuffled: NotRequired[bool]
    play_queue_source_uri: NotRequired[str]
    play_queue_total_count: NotRequired[int]
    play_queue_version: NotRequired[int]


class MediaContainerWithPlayQueue(BaseModel):
    r"""A media container representing a play queue."""

    identifier: Optional[str] = None

    offset: Optional[int] = None
    r"""The offset of where this container page starts among the total objects available. Also provided in the `X-Plex-Container-Start` header."""

    size: Optional[int] = None

    total_size: Annotated[Optional[int], pydantic.Field(alias="totalSize")] = None
    r"""The total size of objects available. Also provided in the `X-Plex-Container-Total-Size` header."""

    play_queue_id: Annotated[Optional[int], pydantic.Field(alias="playQueueID")] = None

    play_queue_last_added_item_id: Annotated[
        Optional[int], pydantic.Field(alias="playQueueLastAddedItemID")
    ] = None

    play_queue_selected_item_id: Annotated[
        Optional[int], pydantic.Field(alias="playQueueSelectedItemID")
    ] = None

    play_queue_selected_item_offset: Annotated[
        Optional[int], pydantic.Field(alias="playQueueSelectedItemOffset")
    ] = None

    play_queue_selected_metadata_item_id: Annotated[
        Optional[int], pydantic.Field(alias="playQueueSelectedMetadataItemID")
    ] = None

    play_queue_shuffled: Annotated[
        Optional[bool], pydantic.Field(alias="playQueueShuffled")
    ] = None

    play_queue_source_uri: Annotated[
        Optional[str], pydantic.Field(alias="playQueueSourceURI")
    ] = None

    play_queue_total_count: Annotated[
        Optional[int], pydantic.Field(alias="playQueueTotalCount")
    ] = None

    play_queue_version: Annotated[
        Optional[int], pydantic.Field(alias="playQueueVersion")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "identifier",
                "offset",
                "size",
                "totalSize",
                "playQueueID",
                "playQueueLastAddedItemID",
                "playQueueSelectedItemID",
                "playQueueSelectedItemOffset",
                "playQueueSelectedMetadataItemID",
                "playQueueShuffled",
                "playQueueSourceURI",
                "playQueueTotalCount",
                "playQueueVersion",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    MediaContainerWithPlayQueue.model_rebuild()
except NameError:
    pass
