"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .playsessionstatenotification import (
    PlaySessionStateNotification,
    PlaySessionStateNotificationTypedDict,
)
from .reachabilitynotification import (
    ReachabilityNotification,
    ReachabilityNotificationTypedDict,
)
from .statusnotification import StatusNotification, StatusNotificationTypedDict
from .timelineentry import TimelineEntry, TimelineEntryTypedDict
from plex_api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class NotificationContainerTypedDict(TypedDict):
    type: NotRequired[str]
    r"""The notification type"""
    play_session_state_notification: NotRequired[
        List[PlaySessionStateNotificationTypedDict]
    ]
    reachability_notification: NotRequired[List[ReachabilityNotificationTypedDict]]
    size: NotRequired[int]
    r"""Number of notifications"""
    status_notification: NotRequired[List[StatusNotificationTypedDict]]
    timeline_entry: NotRequired[List[TimelineEntryTypedDict]]


class NotificationContainer(BaseModel):
    type: Optional[str] = None
    r"""The notification type"""

    play_session_state_notification: Optional[List[PlaySessionStateNotification]] = None

    reachability_notification: Optional[List[ReachabilityNotification]] = None

    size: Optional[int] = None
    r"""Number of notifications"""

    status_notification: Optional[List[StatusNotification]] = None

    timeline_entry: Optional[List[TimelineEntry]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "type",
                "PlaySessionStateNotification",
                "ReachabilityNotification",
                "size",
                "StatusNotification",
                "TimelineEntry",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
