"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlaybackHistoryMetadataTypedDict(TypedDict):
    title: NotRequired[str]
    r"""The title of the item played"""
    type: NotRequired[str]
    r"""The metadata type of the item played"""
    account_id: NotRequired[int]
    r"""The account id of this playback"""
    device_id: NotRequired[int]
    r"""The device id which played the item"""
    grandparent_rating_key: NotRequired[str]
    r"""The rating key of the grandparent item"""
    grandparent_title: NotRequired[str]
    r"""The title of the grandparent item (e.g. show name for an episode)"""
    history_key: NotRequired[str]
    r"""The key for this individual history item"""
    index: NotRequired[int]
    r"""The index of the item (e.g. episode number)"""
    key: NotRequired[str]
    r"""The metadata key for the item played"""
    library_section_id: NotRequired[str]
    r"""The library section id containing the item played"""
    originally_available_at: NotRequired[str]
    r"""The originally available at of the item played"""
    parent_index: NotRequired[int]
    r"""The index of the parent item (e.g. season number)"""
    parent_title: NotRequired[str]
    r"""The title of the parent item (e.g. season name for an episode)"""
    rating_key: NotRequired[str]
    r"""The rating key for the item played"""
    thumb: NotRequired[str]
    r"""The thumb of the item played"""
    viewed_at: NotRequired[int]
    r"""The time when the item was played"""


class PlaybackHistoryMetadata(BaseModel):
    title: Optional[str] = None
    r"""The title of the item played"""

    type: Optional[str] = None
    r"""The metadata type of the item played"""

    account_id: Annotated[Optional[int], pydantic.Field(alias="accountID")] = None
    r"""The account id of this playback"""

    device_id: Annotated[Optional[int], pydantic.Field(alias="deviceID")] = None
    r"""The device id which played the item"""

    grandparent_rating_key: Annotated[
        Optional[str], pydantic.Field(alias="grandparentRatingKey")
    ] = None
    r"""The rating key of the grandparent item"""

    grandparent_title: Annotated[
        Optional[str], pydantic.Field(alias="grandparentTitle")
    ] = None
    r"""The title of the grandparent item (e.g. show name for an episode)"""

    history_key: Annotated[Optional[str], pydantic.Field(alias="historyKey")] = None
    r"""The key for this individual history item"""

    index: Optional[int] = None
    r"""The index of the item (e.g. episode number)"""

    key: Optional[str] = None
    r"""The metadata key for the item played"""

    library_section_id: Annotated[
        Optional[str], pydantic.Field(alias="librarySectionID")
    ] = None
    r"""The library section id containing the item played"""

    originally_available_at: Annotated[
        Optional[str], pydantic.Field(alias="originallyAvailableAt")
    ] = None
    r"""The originally available at of the item played"""

    parent_index: Annotated[Optional[int], pydantic.Field(alias="parentIndex")] = None
    r"""The index of the parent item (e.g. season number)"""

    parent_title: Annotated[Optional[str], pydantic.Field(alias="parentTitle")] = None
    r"""The title of the parent item (e.g. season name for an episode)"""

    rating_key: Annotated[Optional[str], pydantic.Field(alias="ratingKey")] = None
    r"""The rating key for the item played"""

    thumb: Optional[str] = None
    r"""The thumb of the item played"""

    viewed_at: Annotated[Optional[int], pydantic.Field(alias="viewedAt")] = None
    r"""The time when the item was played"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "type",
                "accountID",
                "deviceID",
                "grandparentRatingKey",
                "grandparentTitle",
                "historyKey",
                "index",
                "key",
                "librarySectionID",
                "originallyAvailableAt",
                "parentIndex",
                "parentTitle",
                "ratingKey",
                "thumb",
                "viewedAt",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlaybackHistoryMetadata.model_rebuild()
except NameError:
    pass
