"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from plex_api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class State(str, Enum):
    PLAYING = "playing"
    PAUSED = "paused"
    STOPPED = "stopped"


class PlaySessionStateNotificationTypedDict(TypedDict):
    r"""Real-time playback state change notification"""

    controllable: NotRequired[str]
    guid: NotRequired[str]
    key: NotRequired[str]
    play_queue_id: NotRequired[int]
    play_queue_item_id: NotRequired[int]
    rating_key: NotRequired[str]
    session_key: NotRequired[str]
    state: NotRequired[State]
    transcode_session: NotRequired[str]
    url: NotRequired[str]
    view_offset: NotRequired[int]


class PlaySessionStateNotification(BaseModel):
    r"""Real-time playback state change notification"""

    controllable: Optional[str] = None

    guid: Optional[str] = None

    key: Optional[str] = None

    play_queue_id: Optional[int] = None

    play_queue_item_id: Optional[int] = None

    rating_key: Optional[str] = None

    session_key: Optional[str] = None

    state: Optional[State] = None

    transcode_session: Optional[str] = None

    url: Optional[str] = None

    view_offset: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "controllable",
                "guid",
                "key",
                "playQueueID",
                "playQueueItemID",
                "ratingKey",
                "sessionKey",
                "state",
                "transcodeSession",
                "url",
                "viewOffset",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
