"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlayQueueResponseTypedDict(TypedDict):
    play_queue_id: NotRequired[int]
    r"""The ID of the play queue, which is used in subsequent requests."""
    play_queue_last_added_item_id: NotRequired[str]
    r"""Defines where the \"Up Next\" region starts"""
    play_queue_selected_item_id: NotRequired[int]
    r"""The queue item ID of the currently selected  item."""
    play_queue_selected_item_offset: NotRequired[int]
    r"""The offset of the selected item in the play queue, from the beginning of the queue."""
    play_queue_selected_metadata_item_id: NotRequired[int]
    r"""The metadata item ID of the currently selected item (matches `ratingKey` attribute in metadata item if the media provider is a library)."""
    play_queue_shuffled: NotRequired[bool]
    r"""Whether or not the queue is shuffled."""
    play_queue_source_uri: NotRequired[str]
    r"""The original URI used to create the play queue."""
    play_queue_total_count: NotRequired[int]
    r"""The total number of items in the play queue."""
    play_queue_version: NotRequired[int]
    r"""The version of the play queue. It increments every time a change is made to the play queue to assist clients in knowing when to refresh."""


class PlayQueueResponse(BaseModel):
    play_queue_id: Annotated[Optional[int], pydantic.Field(alias="playQueueID")] = None
    r"""The ID of the play queue, which is used in subsequent requests."""

    play_queue_last_added_item_id: Annotated[
        Optional[str], pydantic.Field(alias="playQueueLastAddedItemID")
    ] = None
    r"""Defines where the \"Up Next\" region starts"""

    play_queue_selected_item_id: Annotated[
        Optional[int], pydantic.Field(alias="playQueueSelectedItemID")
    ] = None
    r"""The queue item ID of the currently selected  item."""

    play_queue_selected_item_offset: Annotated[
        Optional[int], pydantic.Field(alias="playQueueSelectedItemOffset")
    ] = None
    r"""The offset of the selected item in the play queue, from the beginning of the queue."""

    play_queue_selected_metadata_item_id: Annotated[
        Optional[int], pydantic.Field(alias="playQueueSelectedMetadataItemID")
    ] = None
    r"""The metadata item ID of the currently selected item (matches `ratingKey` attribute in metadata item if the media provider is a library)."""

    play_queue_shuffled: Annotated[
        Optional[bool], pydantic.Field(alias="playQueueShuffled")
    ] = None
    r"""Whether or not the queue is shuffled."""

    play_queue_source_uri: Annotated[
        Optional[str], pydantic.Field(alias="playQueueSourceURI")
    ] = None
    r"""The original URI used to create the play queue."""

    play_queue_total_count: Annotated[
        Optional[int], pydantic.Field(alias="playQueueTotalCount")
    ] = None
    r"""The total number of items in the play queue."""

    play_queue_version: Annotated[
        Optional[int], pydantic.Field(alias="playQueueVersion")
    ] = None
    r"""The version of the play queue. It increments every time a change is made to the play queue to assist clients in knowing when to refresh."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "playQueueID",
                "playQueueLastAddedItemID",
                "playQueueSelectedItemID",
                "playQueueSelectedItemOffset",
                "playQueueSelectedMetadataItemID",
                "playQueueShuffled",
                "playQueueSourceURI",
                "playQueueTotalCount",
                "playQueueVersion",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlayQueueResponse.model_rebuild()
except NameError:
    pass
