"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from plex_api_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class PlexDeviceProtocol(str, Enum):
    r"""The protocol used for the connection (http, https, etc)"""

    HTTP = "http"
    HTTPS = "https"


class ConnectionsTypedDict(TypedDict):
    address: str
    r"""The (ip) address or domain name used for the connection"""
    i_pv6: bool
    r"""If the connection is using IPv6"""
    local: bool
    r"""If the connection is local address"""
    port: int
    r"""The port used for the connection"""
    protocol: PlexDeviceProtocol
    r"""The protocol used for the connection (http, https, etc)"""
    relay: bool
    r"""If the connection is relayed through plex.direct"""
    uri: str
    r"""The full URI of the connection"""


class Connections(BaseModel):
    address: str
    r"""The (ip) address or domain name used for the connection"""

    i_pv6: Annotated[bool, pydantic.Field(alias="IPv6")]
    r"""If the connection is using IPv6"""

    local: bool
    r"""If the connection is local address"""

    port: int
    r"""The port used for the connection"""

    protocol: PlexDeviceProtocol
    r"""The protocol used for the connection (http, https, etc)"""

    relay: bool
    r"""If the connection is relayed through plex.direct"""

    uri: str
    r"""The full URI of the connection"""


class PlexDeviceTypedDict(TypedDict):
    access_token: str
    client_identifier: str
    connections: List[ConnectionsTypedDict]
    created_at: datetime
    dns_rebinding_protection: bool
    home: bool
    https_required: bool
    last_seen_at: datetime
    name: str
    nat_loopback_supported: bool
    owned: bool
    owner_id: Nullable[int]
    r"""ownerId is null when the device is owned by the token used to send the request"""
    presence: bool
    product: str
    product_version: str
    provides: str
    public_address: str
    public_address_matches: bool
    relay: bool
    source_title: Nullable[str]
    synced: bool
    device: NotRequired[Nullable[str]]
    platform: NotRequired[Nullable[str]]
    platform_version: NotRequired[Nullable[str]]


class PlexDevice(BaseModel):
    access_token: Annotated[str, pydantic.Field(alias="accessToken")]

    client_identifier: Annotated[str, pydantic.Field(alias="clientIdentifier")]

    connections: List[Connections]

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    dns_rebinding_protection: Annotated[
        bool, pydantic.Field(alias="dnsRebindingProtection")
    ]

    home: bool

    https_required: Annotated[bool, pydantic.Field(alias="httpsRequired")]

    last_seen_at: Annotated[datetime, pydantic.Field(alias="lastSeenAt")]

    name: str

    nat_loopback_supported: Annotated[
        bool, pydantic.Field(alias="natLoopbackSupported")
    ]

    owned: bool

    owner_id: Annotated[Nullable[int], pydantic.Field(alias="ownerId")]
    r"""ownerId is null when the device is owned by the token used to send the request"""

    presence: bool

    product: str

    product_version: Annotated[str, pydantic.Field(alias="productVersion")]

    provides: str

    public_address: Annotated[str, pydantic.Field(alias="publicAddress")]

    public_address_matches: Annotated[
        bool, pydantic.Field(alias="publicAddressMatches")
    ]

    relay: bool

    source_title: Annotated[Nullable[str], pydantic.Field(alias="sourceTitle")]

    synced: bool

    device: OptionalNullable[str] = UNSET

    platform: OptionalNullable[str] = UNSET

    platform_version: Annotated[
        OptionalNullable[str], pydantic.Field(alias="platformVersion")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["device", "platform", "platformVersion"])
        nullable_fields = set(
            ["device", "ownerId", "platform", "platformVersion", "sourceTitle"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    Connections.model_rebuild()
except NameError:
    pass
try:
    PlexDevice.model_rebuild()
except NameError:
    pass
