"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .directory import Directory, DirectoryTypedDict
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlexDownloadsResponseMediaContainerTypedDict(TypedDict):
    directory: NotRequired[List[DirectoryTypedDict]]
    size: NotRequired[int]


class PlexDownloadsResponseMediaContainer(BaseModel):
    directory: Annotated[
        Optional[List[Directory]], pydantic.Field(alias="Directory")
    ] = None

    size: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Directory", "size"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PlexDownloadsResponseTypedDict(TypedDict):
    media_container: NotRequired[PlexDownloadsResponseMediaContainerTypedDict]


class PlexDownloadsResponse(BaseModel):
    media_container: Annotated[
        Optional[PlexDownloadsResponseMediaContainer],
        pydantic.Field(alias="MediaContainer"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["MediaContainer"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PlexDownloadsResponseMediaContainer.model_rebuild()
except NameError:
    pass
try:
    PlexDownloadsResponse.model_rebuild()
except NameError:
    pass
