"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ProviderTypedDict(TypedDict):
    r"""A media provider registered with the PMS."""

    title: NotRequired[str]
    r"""Human-readable provider title."""
    identifier: NotRequired[str]
    r"""Unique provider identifier."""
    protocol: NotRequired[str]
    r"""Protocol version used by the provider."""
    types: NotRequired[str]
    r"""Content types provided."""


class Provider(BaseModel):
    r"""A media provider registered with the PMS."""

    title: Optional[str] = None
    r"""Human-readable provider title."""

    identifier: Optional[str] = None
    r"""Unique provider identifier."""

    protocol: Annotated[Optional[str], pydantic.Field(alias="Protocol")] = None
    r"""Protocol version used by the provider."""

    types: Optional[str] = None
    r"""Content types provided."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["title", "identifier", "Protocol", "types"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Provider.model_rebuild()
except NameError:
    pass
