"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ReleaseState(str, Enum):
    r"""The status of this update.

    - available - This release is available
    - downloading - This release is downloading
    - downloaded - This release has been downloaded
    - installing - This release is installing
    - tonight - This release will be installed tonight
    - skipped - This release has been skipped
    - error - This release has an error
    - notify - This release is only notifying it is available (typically because it cannot be installed on this setup)
    - done - This release is complete
    """

    AVAILABLE = "available"
    DOWNLOADING = "downloading"
    DOWNLOADED = "downloaded"
    INSTALLING = "installing"
    TONIGHT = "tonight"
    SKIPPED = "skipped"
    ERROR = "error"
    NOTIFY = "notify"
    DONE = "done"


class ReleaseTypedDict(TypedDict):
    added: NotRequired[str]
    r"""A list of what has been added in this version"""
    download_url: NotRequired[str]
    r"""The URL of where this update is available"""
    fixed: NotRequired[str]
    r"""A list of what has been fixed in this version"""
    key: NotRequired[str]
    r"""The URL key of the update"""
    state: NotRequired[ReleaseState]
    r"""The status of this update.

    - available - This release is available
    - downloading - This release is downloading
    - downloaded - This release has been downloaded
    - installing - This release is installing
    - tonight - This release will be installed tonight
    - skipped - This release has been skipped
    - error - This release has an error
    - notify - This release is only notifying it is available (typically because it cannot be installed on this setup)
    - done - This release is complete
    """
    version: NotRequired[str]
    r"""The version available"""


class Release(BaseModel):
    added: Optional[str] = None
    r"""A list of what has been added in this version"""

    download_url: Annotated[Optional[str], pydantic.Field(alias="downloadURL")] = None
    r"""The URL of where this update is available"""

    fixed: Optional[str] = None
    r"""A list of what has been fixed in this version"""

    key: Optional[str] = None
    r"""The URL key of the update"""

    state: Optional[ReleaseState] = None
    r"""The status of this update.

    - available - This release is available
    - downloading - This release is downloading
    - downloaded - This release has been downloaded
    - installing - This release is installing
    - tonight - This release will be installed tonight
    - skipped - This release has been skipped
    - error - This release has an error
    - notify - This release is only notifying it is available (typically because it cannot be installed on this setup)
    - done - This release is complete
    """

    version: Optional[str] = None
    r"""The version available"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["added", "downloadURL", "fixed", "key", "state", "version"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Release.model_rebuild()
except NameError:
    pass
