"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from plex_api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class SessionLocation(str, Enum):
    r"""The location of the client"""

    LAN = "lan"
    WAN = "wan"


class SessionTypedDict(TypedDict):
    r"""Information about the playback session"""

    bandwidth: NotRequired[int]
    r"""The bandwidth used by this client's playback in kbps"""
    id: NotRequired[str]
    r"""The id of the playback session"""
    location: NotRequired[SessionLocation]
    r"""The location of the client"""


class Session(BaseModel):
    r"""Information about the playback session"""

    bandwidth: Optional[int] = None
    r"""The bandwidth used by this client's playback in kbps"""

    id: Optional[str] = None
    r"""The id of the playback session"""

    location: Optional[SessionLocation] = None
    r"""The location of the client"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["bandwidth", "id", "location"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
