"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class BitrateMode(str, Enum):
    r"""Audio bitrate mode (cbr or vbr)."""

    CBR = "cbr"
    VBR = "vbr"


class One(str, Enum):
    ZERO = "0"
    ONE = "1"


CanAutoSync2TypedDict = TypeAliasType("CanAutoSync2TypedDict", Union[One, bool])


CanAutoSync2 = TypeAliasType("CanAutoSync2", Union[One, bool])


CanAutoSyncTypedDict = TypeAliasType(
    "CanAutoSyncTypedDict", Union[bool, CanAutoSync2TypedDict]
)
r"""Indicates if the stream can auto-sync."""


CanAutoSync = TypeAliasType("CanAutoSync", Union[bool, CanAutoSync2])
r"""Indicates if the stream can auto-sync."""


class StreamType(int, Enum):
    r"""Stream type:
    - VIDEO = 1 (Video stream)
    - AUDIO = 2 (Audio stream)
    - SUBTITLE = 3 (Subtitle stream)
    """

    VIDEO = 1
    AUDIO = 2
    SUBTITLE = 3


class StreamTypedDict(TypedDict):
    r"""`Stream` represents a particular stream from a media item, such as the video stream, audio stream, or subtitle stream. The stream may either be part of the file represented by the parent `Part` or, especially for subtitles, an external file. The stream contains more detailed information about the specific stream. For example, a video may include the `aspectRatio` at the `Media` level, but detailed information about the video stream like the color space will be included on the `Stream` for the video stream.  Note that photos do not have streams (mostly as an optimization)."""

    codec: str
    r"""Codec used by the stream."""
    display_title: str
    r"""Display title for the stream."""
    id: int
    r"""Unique stream identifier."""
    key: str
    r"""Key to access this stream part."""
    stream_type: StreamType
    title: NotRequired[str]
    r"""Optional title for the stream (e.g., language variant)."""
    format_: NotRequired[str]
    r"""Format of the stream (e.g., srt)."""
    default: NotRequired[bool]
    r"""Indicates if this stream is default."""
    album_gain: NotRequired[float]
    r"""ReplayGain album gain in dB."""
    album_peak: NotRequired[float]
    r"""ReplayGain album peak amplitude."""
    album_range: NotRequired[float]
    r"""ReplayGain album dynamic range in dB."""
    audio_channel_layout: NotRequired[str]
    r"""Audio channel layout."""
    bit_depth: NotRequired[int]
    r"""Bit depth of the video stream."""
    bitrate: NotRequired[int]
    r"""Bitrate of the stream."""
    bitrate_mode: NotRequired[BitrateMode]
    r"""Audio bitrate mode (cbr or vbr)."""
    can_auto_sync: NotRequired[CanAutoSyncTypedDict]
    r"""Indicates if the stream can auto-sync."""
    channels: NotRequired[int]
    r"""Number of audio channels (for audio streams)."""
    chroma_location: NotRequired[str]
    r"""Chroma sample location."""
    chroma_subsampling: NotRequired[str]
    r"""Chroma subsampling format."""
    closed_captions: NotRequired[bool]
    coded_height: NotRequired[int]
    r"""Coded video height."""
    coded_width: NotRequired[int]
    r"""Coded video width."""
    color_primaries: NotRequired[str]
    r"""Color primaries used."""
    color_range: NotRequired[str]
    r"""Color range (e.g., tv)."""
    color_space: NotRequired[str]
    r"""Color space."""
    color_trc: NotRequired[str]
    r"""Color transfer characteristics."""
    dovibl_compat_id: NotRequired[int]
    r"""Dolby Vision BL compatibility ID."""
    dovibl_present: NotRequired[bool]
    r"""Indicates if Dolby Vision BL is present."""
    doviel_present: NotRequired[bool]
    r"""Indicates if Dolby Vision EL is present."""
    dovi_level: NotRequired[int]
    r"""Dolby Vision level."""
    dovi_present: NotRequired[bool]
    r"""Indicates if Dolby Vision is present."""
    dovi_profile: NotRequired[int]
    r"""Dolby Vision profile."""
    dovirpu_present: NotRequired[bool]
    r"""Indicates if Dolby Vision RPU is present."""
    dovi_version: NotRequired[str]
    r"""Dolby Vision version."""
    dub: NotRequired[bool]
    r"""Indicates if the stream is a dub."""
    embedded_in_video: NotRequired[str]
    end_ramp: NotRequired[str]
    r"""Loudness ramp end type."""
    extended_display_title: NotRequired[str]
    r"""Extended display title for the stream."""
    forced: NotRequired[bool]
    frame_rate: NotRequired[float]
    r"""Frame rate of the stream."""
    gain: NotRequired[float]
    r"""Track replay gain in dB."""
    has_scaling_matrix: NotRequired[bool]
    header_compression: NotRequired[bool]
    r"""Indicates whether header compression is enabled."""
    hearing_impaired: NotRequired[bool]
    r"""Indicates if the stream is for the hearing impaired."""
    height: NotRequired[int]
    r"""Height of the video stream."""
    index: NotRequired[int]
    r"""Index of the stream."""
    language: NotRequired[str]
    r"""Language of the stream."""
    language_code: NotRequired[str]
    r"""ISO language code."""
    language_tag: NotRequired[str]
    r"""Language tag (e.g., en)."""
    level: NotRequired[int]
    r"""Video level."""
    loudness: NotRequired[float]
    r"""Integrated loudness in LUFS."""
    lra: NotRequired[float]
    r"""Loudness range in LU."""
    min_lines: NotRequired[int]
    r"""Minimum lines in the lyric file."""
    original: NotRequired[bool]
    r"""Indicates if this is the original stream."""
    peak: NotRequired[float]
    r"""Track peak amplitude."""
    perfect_match: NotRequired[bool]
    r"""Whether the subtitle is an exact match."""
    profile: NotRequired[str]
    r"""Video profile."""
    provider: NotRequired[str]
    r"""Lyric or subtitle provider name."""
    provider_title: NotRequired[str]
    r"""Subtitle provider display name."""
    ref_frames: NotRequired[int]
    r"""Number of reference frames."""
    sampling_rate: NotRequired[int]
    r"""Sampling rate for the audio stream."""
    scan_type: NotRequired[str]
    score: NotRequired[float]
    r"""Subtitle match confidence score (0-100)."""
    selected: NotRequired[bool]
    r"""Indicates if this stream is selected (applicable for audio streams)."""
    source_key: NotRequired[str]
    r"""Source identifier for the subtitle."""
    start_ramp: NotRequired[str]
    r"""Loudness ramp start type."""
    stream_identifier: NotRequired[int]
    timed: NotRequired[bool]
    r"""Whether lyrics are timestamped."""
    transient: NotRequired[bool]
    r"""Whether the subtitle is temporary or downloaded."""
    user_id: NotRequired[int]
    r"""ID of the user who added the subtitle."""
    visual_impaired: NotRequired[bool]
    r"""Whether this audio track is an audio description track."""
    width: NotRequired[int]
    r"""Width of the video stream."""


class Stream(BaseModel):
    r"""`Stream` represents a particular stream from a media item, such as the video stream, audio stream, or subtitle stream. The stream may either be part of the file represented by the parent `Part` or, especially for subtitles, an external file. The stream contains more detailed information about the specific stream. For example, a video may include the `aspectRatio` at the `Media` level, but detailed information about the video stream like the color space will be included on the `Stream` for the video stream.  Note that photos do not have streams (mostly as an optimization)."""

    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    codec: str
    r"""Codec used by the stream."""

    display_title: Annotated[str, pydantic.Field(alias="displayTitle")]
    r"""Display title for the stream."""

    id: int
    r"""Unique stream identifier."""

    key: str
    r"""Key to access this stream part."""

    stream_type: Annotated[StreamType, pydantic.Field(alias="streamType")]

    title: Optional[str] = None
    r"""Optional title for the stream (e.g., language variant)."""

    format_: Annotated[Optional[str], pydantic.Field(alias="format")] = None
    r"""Format of the stream (e.g., srt)."""

    default: Optional[bool] = None
    r"""Indicates if this stream is default."""

    album_gain: Annotated[Optional[float], pydantic.Field(alias="albumGain")] = None
    r"""ReplayGain album gain in dB."""

    album_peak: Annotated[Optional[float], pydantic.Field(alias="albumPeak")] = None
    r"""ReplayGain album peak amplitude."""

    album_range: Annotated[Optional[float], pydantic.Field(alias="albumRange")] = None
    r"""ReplayGain album dynamic range in dB."""

    audio_channel_layout: Annotated[
        Optional[str], pydantic.Field(alias="audioChannelLayout")
    ] = None
    r"""Audio channel layout."""

    bit_depth: Annotated[Optional[int], pydantic.Field(alias="bitDepth")] = None
    r"""Bit depth of the video stream."""

    bitrate: Optional[int] = None
    r"""Bitrate of the stream."""

    bitrate_mode: Annotated[
        Optional[BitrateMode], pydantic.Field(alias="bitrateMode")
    ] = None
    r"""Audio bitrate mode (cbr or vbr)."""

    can_auto_sync: Annotated[
        Optional[CanAutoSync], pydantic.Field(alias="canAutoSync")
    ] = None
    r"""Indicates if the stream can auto-sync."""

    channels: Optional[int] = None
    r"""Number of audio channels (for audio streams)."""

    chroma_location: Annotated[
        Optional[str], pydantic.Field(alias="chromaLocation")
    ] = None
    r"""Chroma sample location."""

    chroma_subsampling: Annotated[
        Optional[str], pydantic.Field(alias="chromaSubsampling")
    ] = None
    r"""Chroma subsampling format."""

    closed_captions: Annotated[
        Optional[bool], pydantic.Field(alias="closedCaptions")
    ] = None

    coded_height: Annotated[Optional[int], pydantic.Field(alias="codedHeight")] = None
    r"""Coded video height."""

    coded_width: Annotated[Optional[int], pydantic.Field(alias="codedWidth")] = None
    r"""Coded video width."""

    color_primaries: Annotated[
        Optional[str], pydantic.Field(alias="colorPrimaries")
    ] = None
    r"""Color primaries used."""

    color_range: Annotated[Optional[str], pydantic.Field(alias="colorRange")] = None
    r"""Color range (e.g., tv)."""

    color_space: Annotated[Optional[str], pydantic.Field(alias="colorSpace")] = None
    r"""Color space."""

    color_trc: Annotated[Optional[str], pydantic.Field(alias="colorTrc")] = None
    r"""Color transfer characteristics."""

    dovibl_compat_id: Annotated[
        Optional[int], pydantic.Field(alias="DOVIBLCompatID")
    ] = None
    r"""Dolby Vision BL compatibility ID."""

    dovibl_present: Annotated[Optional[bool], pydantic.Field(alias="DOVIBLPresent")] = (
        None
    )
    r"""Indicates if Dolby Vision BL is present."""

    doviel_present: Annotated[Optional[bool], pydantic.Field(alias="DOVIELPresent")] = (
        None
    )
    r"""Indicates if Dolby Vision EL is present."""

    dovi_level: Annotated[Optional[int], pydantic.Field(alias="DOVILevel")] = None
    r"""Dolby Vision level."""

    dovi_present: Annotated[Optional[bool], pydantic.Field(alias="DOVIPresent")] = None
    r"""Indicates if Dolby Vision is present."""

    dovi_profile: Annotated[Optional[int], pydantic.Field(alias="DOVIProfile")] = None
    r"""Dolby Vision profile."""

    dovirpu_present: Annotated[
        Optional[bool], pydantic.Field(alias="DOVIRPUPresent")
    ] = None
    r"""Indicates if Dolby Vision RPU is present."""

    dovi_version: Annotated[Optional[str], pydantic.Field(alias="DOVIVersion")] = None
    r"""Dolby Vision version."""

    dub: Optional[bool] = None
    r"""Indicates if the stream is a dub."""

    embedded_in_video: Annotated[
        Optional[str], pydantic.Field(alias="embeddedInVideo")
    ] = None

    end_ramp: Annotated[Optional[str], pydantic.Field(alias="endRamp")] = None
    r"""Loudness ramp end type."""

    extended_display_title: Annotated[
        Optional[str], pydantic.Field(alias="extendedDisplayTitle")
    ] = None
    r"""Extended display title for the stream."""

    forced: Optional[bool] = None

    frame_rate: Annotated[Optional[float], pydantic.Field(alias="frameRate")] = None
    r"""Frame rate of the stream."""

    gain: Optional[float] = None
    r"""Track replay gain in dB."""

    has_scaling_matrix: Annotated[
        Optional[bool], pydantic.Field(alias="hasScalingMatrix")
    ] = None

    header_compression: Annotated[
        Optional[bool], pydantic.Field(alias="headerCompression")
    ] = None
    r"""Indicates whether header compression is enabled."""

    hearing_impaired: Annotated[
        Optional[bool], pydantic.Field(alias="hearingImpaired")
    ] = None
    r"""Indicates if the stream is for the hearing impaired."""

    height: Optional[int] = None
    r"""Height of the video stream."""

    index: Optional[int] = None
    r"""Index of the stream."""

    language: Optional[str] = None
    r"""Language of the stream."""

    language_code: Annotated[Optional[str], pydantic.Field(alias="languageCode")] = None
    r"""ISO language code."""

    language_tag: Annotated[Optional[str], pydantic.Field(alias="languageTag")] = None
    r"""Language tag (e.g., en)."""

    level: Optional[int] = None
    r"""Video level."""

    loudness: Optional[float] = None
    r"""Integrated loudness in LUFS."""

    lra: Optional[float] = None
    r"""Loudness range in LU."""

    min_lines: Annotated[Optional[int], pydantic.Field(alias="minLines")] = None
    r"""Minimum lines in the lyric file."""

    original: Optional[bool] = None
    r"""Indicates if this is the original stream."""

    peak: Optional[float] = None
    r"""Track peak amplitude."""

    perfect_match: Annotated[Optional[bool], pydantic.Field(alias="perfectMatch")] = (
        None
    )
    r"""Whether the subtitle is an exact match."""

    profile: Optional[str] = None
    r"""Video profile."""

    provider: Optional[str] = None
    r"""Lyric or subtitle provider name."""

    provider_title: Annotated[Optional[str], pydantic.Field(alias="providerTitle")] = (
        None
    )
    r"""Subtitle provider display name."""

    ref_frames: Annotated[Optional[int], pydantic.Field(alias="refFrames")] = None
    r"""Number of reference frames."""

    sampling_rate: Annotated[Optional[int], pydantic.Field(alias="samplingRate")] = None
    r"""Sampling rate for the audio stream."""

    scan_type: Annotated[Optional[str], pydantic.Field(alias="scanType")] = None

    score: Optional[float] = None
    r"""Subtitle match confidence score (0-100)."""

    selected: Optional[bool] = None
    r"""Indicates if this stream is selected (applicable for audio streams)."""

    source_key: Annotated[Optional[str], pydantic.Field(alias="sourceKey")] = None
    r"""Source identifier for the subtitle."""

    start_ramp: Annotated[Optional[str], pydantic.Field(alias="startRamp")] = None
    r"""Loudness ramp start type."""

    stream_identifier: Annotated[
        Optional[int], pydantic.Field(alias="streamIdentifier")
    ] = None

    timed: Optional[bool] = None
    r"""Whether lyrics are timestamped."""

    transient: Optional[bool] = None
    r"""Whether the subtitle is temporary or downloaded."""

    user_id: Annotated[Optional[int], pydantic.Field(alias="userID")] = None
    r"""ID of the user who added the subtitle."""

    visual_impaired: Annotated[
        Optional[bool], pydantic.Field(alias="visualImpaired")
    ] = None
    r"""Whether this audio track is an audio description track."""

    width: Optional[int] = None
    r"""Width of the video stream."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__

    @additional_properties.setter
    def additional_properties(self, value):
        self.__pydantic_extra__ = value  # pyright: ignore[reportIncompatibleVariableOverride]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "format",
                "default",
                "albumGain",
                "albumPeak",
                "albumRange",
                "audioChannelLayout",
                "bitDepth",
                "bitrate",
                "bitrateMode",
                "canAutoSync",
                "channels",
                "chromaLocation",
                "chromaSubsampling",
                "closedCaptions",
                "codedHeight",
                "codedWidth",
                "colorPrimaries",
                "colorRange",
                "colorSpace",
                "colorTrc",
                "DOVIBLCompatID",
                "DOVIBLPresent",
                "DOVIELPresent",
                "DOVILevel",
                "DOVIPresent",
                "DOVIProfile",
                "DOVIRPUPresent",
                "DOVIVersion",
                "dub",
                "embeddedInVideo",
                "endRamp",
                "extendedDisplayTitle",
                "forced",
                "frameRate",
                "gain",
                "hasScalingMatrix",
                "headerCompression",
                "hearingImpaired",
                "height",
                "index",
                "language",
                "languageCode",
                "languageTag",
                "level",
                "loudness",
                "lra",
                "minLines",
                "original",
                "peak",
                "perfectMatch",
                "profile",
                "provider",
                "providerTitle",
                "refFrames",
                "samplingRate",
                "scanType",
                "score",
                "selected",
                "sourceKey",
                "startRamp",
                "streamIdentifier",
                "timed",
                "transient",
                "userID",
                "visualImpaired",
                "width",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            serialized.pop(k, serialized.pop(n, None))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val
        for k, v in serialized.items():
            m[k] = v

        return m


try:
    Stream.model_rebuild()
except NameError:
    pass
