"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class TimelineEntryTypedDict(TypedDict):
    r"""A timeline update entry delivered via WebSocket or EventSource"""

    title: NotRequired[str]
    type: NotRequired[int]
    item_id: NotRequired[int]
    metadata_state: NotRequired[str]
    play_queue_item_id: NotRequired[int]
    state: NotRequired[int]


class TimelineEntry(BaseModel):
    r"""A timeline update entry delivered via WebSocket or EventSource"""

    title: Optional[str] = None

    type: Optional[int] = None

    item_id: Optional[int] = None

    metadata_state: Optional[str] = None

    play_queue_item_id: Optional[int] = None

    state: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["title", "type", "itemID", "metadataState", "playQueueItemID", "state"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
