"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TokenExchangeRequestTypedDict(TypedDict):
    client_identifier: NotRequired[str]
    r"""Unique client identifier"""
    jwt: NotRequired[str]
    r"""JWT token to exchange for a Plex auth token"""
    scope: NotRequired[str]
    r"""Requested scope for the token"""


class TokenExchangeRequest(BaseModel):
    client_identifier: Annotated[
        Optional[str], pydantic.Field(alias="clientIdentifier")
    ] = None
    r"""Unique client identifier"""

    jwt: Optional[str] = None
    r"""JWT token to exchange for a Plex auth token"""

    scope: Optional[str] = None
    r"""Requested scope for the token"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["clientIdentifier", "jwt", "scope"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TokenExchangeRequest.model_rebuild()
except NameError:
    pass
