"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TranscodeSessionTypedDict(TypedDict):
    r"""The transcode session if item is currently being transcoded"""

    complete: NotRequired[bool]
    context: NotRequired[str]
    duration: NotRequired[int]
    error: NotRequired[bool]
    key: NotRequired[str]
    progress: NotRequired[float]
    protocol: NotRequired[str]
    size: NotRequired[int]
    source_audio_codec: NotRequired[str]
    source_video_codec: NotRequired[str]
    speed: NotRequired[float]
    throttled: NotRequired[bool]
    transcode_hw_full_pipeline: NotRequired[bool]
    transcode_hw_requested: NotRequired[bool]


class TranscodeSession(BaseModel):
    r"""The transcode session if item is currently being transcoded"""

    complete: Optional[bool] = None

    context: Optional[str] = None

    duration: Optional[int] = None

    error: Optional[bool] = None

    key: Optional[str] = None

    progress: Optional[float] = None

    protocol: Optional[str] = None

    size: Optional[int] = None

    source_audio_codec: Annotated[
        Optional[str], pydantic.Field(alias="sourceAudioCodec")
    ] = None

    source_video_codec: Annotated[
        Optional[str], pydantic.Field(alias="sourceVideoCodec")
    ] = None

    speed: Optional[float] = None

    throttled: Optional[bool] = None

    transcode_hw_full_pipeline: Annotated[
        Optional[bool], pydantic.Field(alias="transcodeHwFullPipeline")
    ] = None

    transcode_hw_requested: Annotated[
        Optional[bool], pydantic.Field(alias="transcodeHwRequested")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "complete",
                "context",
                "duration",
                "error",
                "key",
                "progress",
                "protocol",
                "size",
                "sourceAudioCodec",
                "sourceVideoCodec",
                "speed",
                "throttled",
                "transcodeHwFullPipeline",
                "transcodeHwRequested",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TranscodeSession.model_rebuild()
except NameError:
    pass
