"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class TranscodeJobType(str, Enum):
    TRANSCODE = "transcode"


class TranscodeJobTypedDict(TypedDict):
    title: NotRequired[str]
    type: NotRequired[TranscodeJobType]
    generator_id: NotRequired[int]
    key: NotRequired[str]
    progress: NotRequired[float]
    rating_key: NotRequired[str]
    remaining: NotRequired[int]
    r"""The number of seconds remaining in this job"""
    size: NotRequired[int]
    r"""The size of the result so far"""
    speed: NotRequired[float]
    r"""The speed of the transcode; 1.0 means real-time"""
    target_tag_id: NotRequired[int]
    r"""The tag associated with the job.  This could be the tag containing the optimizer settings."""
    thumb: NotRequired[str]


class TranscodeJob(BaseModel):
    title: Optional[str] = None

    type: Optional[TranscodeJobType] = None

    generator_id: Annotated[Optional[int], pydantic.Field(alias="generatorID")] = None

    key: Optional[str] = None

    progress: Optional[float] = None

    rating_key: Annotated[Optional[str], pydantic.Field(alias="ratingKey")] = None

    remaining: Optional[int] = None
    r"""The number of seconds remaining in this job"""

    size: Optional[int] = None
    r"""The size of the result so far"""

    speed: Optional[float] = None
    r"""The speed of the transcode; 1.0 means real-time"""

    target_tag_id: Annotated[Optional[int], pydantic.Field(alias="targetTagID")] = None
    r"""The tag associated with the job.  This could be the tag containing the optimizer settings."""

    thumb: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "type",
                "generatorID",
                "key",
                "progress",
                "ratingKey",
                "remaining",
                "size",
                "speed",
                "targetTagID",
                "thumb",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    TranscodeJob.model_rebuild()
except NameError:
    pass
