"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AccountTypedDict(TypedDict):
    title: NotRequired[str]
    id: NotRequired[int]
    thumb: NotRequired[str]


class Account(BaseModel):
    title: Optional[str] = None

    id: Optional[int] = None

    thumb: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["title", "id", "thumb"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Event(str, Enum):
    r"""Event type that triggered the webhook."""

    MEDIA_PLAY = "media.play"
    MEDIA_PAUSE = "media.pause"
    MEDIA_RESUME = "media.resume"
    MEDIA_STOP = "media.stop"
    MEDIA_SCROBBLE = "media.scrobble"
    MEDIA_RATE = "media.rate"
    LIBRARY_NEW = "library.new"
    LIBRARY_ON_DECK = "library.on.deck"


class WebhookPayloadMetadataTypedDict(TypedDict):
    r"""The media item associated with the event. Shape varies by event type."""


class WebhookPayloadMetadata(BaseModel):
    r"""The media item associated with the event. Shape varies by event type."""


class WebhookPayloadPlayerTypedDict(TypedDict):
    title: NotRequired[str]
    local: NotRequired[bool]
    public_address: NotRequired[str]
    uuid: NotRequired[str]


class WebhookPayloadPlayer(BaseModel):
    title: Optional[str] = None

    local: Optional[bool] = None

    public_address: Annotated[Optional[str], pydantic.Field(alias="publicAddress")] = (
        None
    )

    uuid: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["title", "local", "publicAddress", "uuid"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ServerTypedDict(TypedDict):
    title: NotRequired[str]
    uuid: NotRequired[str]


class Server(BaseModel):
    title: Optional[str] = None

    uuid: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["title", "uuid"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class WebhookPayloadTypedDict(TypedDict):
    r"""Payload delivered by Plex to configured webhook URLs."""

    account: NotRequired[AccountTypedDict]
    event: NotRequired[Event]
    r"""Event type that triggered the webhook."""
    metadata: NotRequired[WebhookPayloadMetadataTypedDict]
    r"""The media item associated with the event. Shape varies by event type."""
    owner: NotRequired[bool]
    player: NotRequired[WebhookPayloadPlayerTypedDict]
    server: NotRequired[ServerTypedDict]
    user: NotRequired[bool]


class WebhookPayload(BaseModel):
    r"""Payload delivered by Plex to configured webhook URLs."""

    account: Annotated[Optional[Account], pydantic.Field(alias="Account")] = None

    event: Optional[Event] = None
    r"""Event type that triggered the webhook."""

    metadata: Annotated[
        Optional[WebhookPayloadMetadata], pydantic.Field(alias="Metadata")
    ] = None
    r"""The media item associated with the event. Shape varies by event type."""

    owner: Optional[bool] = None

    player: Annotated[
        Optional[WebhookPayloadPlayer], pydantic.Field(alias="Player")
    ] = None

    server: Annotated[Optional[Server], pydantic.Field(alias="Server")] = None

    user: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["Account", "event", "Metadata", "owner", "Player", "Server", "user"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    WebhookPayloadPlayer.model_rebuild()
except NameError:
    pass
try:
    WebhookPayload.model_rebuild()
except NameError:
    pass
