"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .plexapierror import PlexAPIError
from typing import Any, TYPE_CHECKING

from plex_api_client.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .badrequest import (
        BadRequest,
        BadRequestData,
        BadRequestErrors,
        BadRequestErrorsTypedDict,
    )
    from .error import Error, ErrorData, Errors, ErrorsTypedDict
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError
    from .sdkerror import SDKError
    from .unauthorized import (
        Unauthorized,
        UnauthorizedData,
        UnauthorizedErrors,
        UnauthorizedErrorsTypedDict,
    )

__all__ = [
    "BadRequest",
    "BadRequestData",
    "BadRequestErrors",
    "BadRequestErrorsTypedDict",
    "Error",
    "ErrorData",
    "Errors",
    "ErrorsTypedDict",
    "NoResponseError",
    "PlexAPIError",
    "ResponseValidationError",
    "SDKError",
    "Unauthorized",
    "UnauthorizedData",
    "UnauthorizedErrors",
    "UnauthorizedErrorsTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "BadRequest": ".badrequest",
    "BadRequestData": ".badrequest",
    "BadRequestErrors": ".badrequest",
    "BadRequestErrorsTypedDict": ".badrequest",
    "Error": ".error",
    "ErrorData": ".error",
    "Errors": ".error",
    "ErrorsTypedDict": ".error",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
    "SDKError": ".sdkerror",
    "Unauthorized": ".unauthorized",
    "UnauthorizedData": ".unauthorized",
    "UnauthorizedErrors": ".unauthorized",
    "UnauthorizedErrorsTypedDict": ".unauthorized",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
