"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import httpx
from plex_api_client.models.components import (
    mediacontainerwithdevice as components_mediacontainerwithdevice,
)
from plex_api_client.types import BaseModel, UNSET_SENTINEL
from plex_api_client.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Protocol(str, Enum):
    r"""Protocol to filter discovery."""

    STREAM = "stream"
    DOWNLOAD = "download"
    LIVETV = "livetv"


class DiscoverDevicesRequestTypedDict(TypedDict):
    protocol: NotRequired[Protocol]
    r"""Protocol to filter discovery."""
    grabber_identifier: NotRequired[str]
    r"""Targeted grabber identifier."""


class DiscoverDevicesRequest(BaseModel):
    protocol: Annotated[
        Optional[Protocol],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Protocol to filter discovery."""

    grabber_identifier: Annotated[
        Optional[str],
        pydantic.Field(alias="grabberIdentifier"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Targeted grabber identifier."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["protocol", "grabberIdentifier"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DiscoverDevicesResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    media_container_with_device: NotRequired[
        components_mediacontainerwithdevice.MediaContainerWithDeviceTypedDict
    ]
    r"""OK"""


class DiscoverDevicesResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    media_container_with_device: Optional[
        components_mediacontainerwithdevice.MediaContainerWithDevice
    ] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["MediaContainerWithDevice"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
