"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from plex_api_client.models.components import (
    mediacontainerwithmetadata as components_mediacontainerwithmetadata,
)
from plex_api_client.types import BaseModel, UNSET_SENTINEL
from plex_api_client.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSessionsRequestTypedDict(TypedDict):
    dvr_id: NotRequired[int]
    r"""Filter by DVR ID."""
    channel: NotRequired[int]
    r"""Filter by channel ID."""


class GetSessionsRequest(BaseModel):
    dvr_id: Annotated[
        Optional[int],
        pydantic.Field(alias="dvrId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by DVR ID."""

    channel: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by channel ID."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["dvrId", "channel"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetSessionsResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    headers: Dict[str, List[str]]
    media_container_with_metadata: NotRequired[
        components_mediacontainerwithmetadata.MediaContainerWithMetadataTypedDict
    ]
    r"""OK"""


class GetSessionsResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    headers: Dict[str, List[str]]

    media_container_with_metadata: Optional[
        components_mediacontainerwithmetadata.MediaContainerWithMetadata
    ] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["MediaContainerWithMetadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
