"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetTasksButlerTaskTypedDict(TypedDict):
    description: NotRequired[str]
    r"""A user-friendly description of the task"""
    enabled: NotRequired[bool]
    r"""Whether this task is enabled or not"""
    interval: NotRequired[int]
    r"""The interval (in days) of when this task is run.  A value of 1 is run every day, 7 is every week, etc."""
    name: NotRequired[str]
    r"""The name of the task"""
    schedule_randomized: NotRequired[bool]
    r"""Indicates whether the timing of the task is randomized within the butler interval"""
    title: NotRequired[str]
    r"""A user-friendly title of the task"""


class GetTasksButlerTask(BaseModel):
    description: Optional[str] = None
    r"""A user-friendly description of the task"""

    enabled: Optional[bool] = None
    r"""Whether this task is enabled or not"""

    interval: Optional[int] = None
    r"""The interval (in days) of when this task is run.  A value of 1 is run every day, 7 is every week, etc."""

    name: Optional[str] = None
    r"""The name of the task"""

    schedule_randomized: Annotated[
        Optional[bool], pydantic.Field(alias="scheduleRandomized")
    ] = None
    r"""Indicates whether the timing of the task is randomized within the butler interval"""

    title: Optional[str] = None
    r"""A user-friendly title of the task"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "description",
                "enabled",
                "interval",
                "name",
                "scheduleRandomized",
                "title",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ButlerTasksTypedDict(TypedDict):
    butler_task: NotRequired[List[GetTasksButlerTaskTypedDict]]


class ButlerTasks(BaseModel):
    butler_task: Annotated[
        Optional[List[GetTasksButlerTask]], pydantic.Field(alias="ButlerTask")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ButlerTask"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetTasksResponseBodyTypedDict(TypedDict):
    r"""Butler tasks"""

    butler_tasks: NotRequired[ButlerTasksTypedDict]


class GetTasksResponseBody(BaseModel):
    r"""Butler tasks"""

    butler_tasks: Annotated[
        Optional[ButlerTasks], pydantic.Field(alias="ButlerTasks")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ButlerTasks"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetTasksResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: NotRequired[GetTasksResponseBodyTypedDict]
    r"""Butler tasks"""


class GetTasksResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    object: Optional[GetTasksResponseBody] = None
    r"""Butler tasks"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GetTasksButlerTask.model_rebuild()
except NameError:
    pass
try:
    ButlerTasks.model_rebuild()
except NameError:
    pass
try:
    GetTasksResponseBody.model_rebuild()
except NameError:
    pass
