"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from plex_api_client.models.components import release as components_release
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetUpdatesStatusMediaContainerTypedDict(TypedDict):
    auto_update_version: NotRequired[int]
    r"""The version of the updater (currently `1`)"""
    can_install: NotRequired[bool]
    r"""Indicates whether this install can be updated through these endpoints (typically only on MacOS and Windows)"""
    checked_at: NotRequired[int]
    r"""The last time a check for updates was performed"""
    download_url: NotRequired[str]
    r"""The URL where the update is available"""
    release: NotRequired[List[components_release.ReleaseTypedDict]]
    status: NotRequired[int]
    r"""The current error code (`0` means no error)"""


class GetUpdatesStatusMediaContainer(BaseModel):
    auto_update_version: Annotated[
        Optional[int], pydantic.Field(alias="autoUpdateVersion")
    ] = None
    r"""The version of the updater (currently `1`)"""

    can_install: Annotated[Optional[bool], pydantic.Field(alias="canInstall")] = None
    r"""Indicates whether this install can be updated through these endpoints (typically only on MacOS and Windows)"""

    checked_at: Annotated[Optional[int], pydantic.Field(alias="checkedAt")] = None
    r"""The last time a check for updates was performed"""

    download_url: Annotated[Optional[str], pydantic.Field(alias="downloadURL")] = None
    r"""The URL where the update is available"""

    release: Annotated[
        Optional[List[components_release.Release]], pydantic.Field(alias="Release")
    ] = None

    status: Optional[int] = None
    r"""The current error code (`0` means no error)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "autoUpdateVersion",
                "canInstall",
                "checkedAt",
                "downloadURL",
                "Release",
                "status",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetUpdatesStatusResponseBodyTypedDict(TypedDict):
    r"""Status of the PMS updater."""

    media_container: NotRequired[GetUpdatesStatusMediaContainerTypedDict]
    checked_at: NotRequired[int]
    r"""Timestamp of the last update check."""
    download_url: NotRequired[str]
    r"""The URL where the update is available."""
    release: NotRequired[List[components_release.ReleaseTypedDict]]
    status: NotRequired[int]
    r"""The current error code (0 means no error)."""


class GetUpdatesStatusResponseBody(BaseModel):
    r"""Status of the PMS updater."""

    media_container: Annotated[
        Optional[GetUpdatesStatusMediaContainer], pydantic.Field(alias="MediaContainer")
    ] = None

    checked_at: Annotated[Optional[int], pydantic.Field(alias="checkedAt")] = None
    r"""Timestamp of the last update check."""

    download_url: Annotated[Optional[str], pydantic.Field(alias="downloadURL")] = None
    r"""The URL where the update is available."""

    release: Annotated[
        Optional[List[components_release.Release]], pydantic.Field(alias="Release")
    ] = None

    status: Optional[int] = None
    r"""The current error code (0 means no error)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["MediaContainer", "checkedAt", "downloadURL", "Release", "status"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetUpdatesStatusResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: NotRequired[GetUpdatesStatusResponseBodyTypedDict]
    r"""OK"""


class GetUpdatesStatusResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    object: Optional[GetUpdatesStatusResponseBody] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GetUpdatesStatusMediaContainer.model_rebuild()
except NameError:
    pass
try:
    GetUpdatesStatusResponseBody.model_rebuild()
except NameError:
    pass
