"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import httpx
from plex_api_client.models.components import (
    successresponse as components_successresponse,
)
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


LINK_O_AUTH_PIN_SERVERS = [
    "https://plex.tv/api/v2",
]


class LinkOAuthPinAuthenticationRequestBodyTypedDict(TypedDict):
    auth_token: NotRequired[str]
    pin: NotRequired[str]


class LinkOAuthPinAuthenticationRequestBody(BaseModel):
    auth_token: Annotated[Optional[str], pydantic.Field(alias="authToken")] = None

    pin: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["authToken", "pin"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class LinkOAuthPinResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    success_response: NotRequired[components_successresponse.SuccessResponseTypedDict]
    r"""OK"""


class LinkOAuthPinResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    success_response: Optional[components_successresponse.SuccessResponse] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["SuccessResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    LinkOAuthPinAuthenticationRequestBody.model_rebuild()
except NameError:
    pass
