"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import httpx
from plex_api_client.models.components import provider as components_provider
from plex_api_client.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListProvidersMediaContainerTypedDict(TypedDict):
    provider: NotRequired[List[components_provider.ProviderTypedDict]]


class ListProvidersMediaContainer(BaseModel):
    provider: Annotated[
        Optional[List[components_provider.Provider]], pydantic.Field(alias="Provider")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Provider"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class Key(str, Enum):
    r"""Feature key identifier."""

    SEARCH = "search"
    METADATA = "metadata"
    CONTENT = "content"
    MATCH = "match"
    MANAGE = "manage"
    TIMELINE = "timeline"
    RATE = "rate"
    PLAYQUEUE = "playqueue"
    PLAYLIST = "playlist"
    SUBSCRIBE = "subscribe"
    PROMOTED = "promoted"
    CONTINUEWATCHING = "continuewatching"
    COLLECTION = "collection"
    ACTIONS = "actions"
    IMAGETRANSCODER = "imagetranscoder"
    QUERY_PARSER = "queryParser"
    GRID = "grid"


class ListProvidersResponseBodyTypedDict(TypedDict):
    r"""A feature supported by a media provider."""

    media_container: NotRequired[ListProvidersMediaContainerTypedDict]
    title: NotRequired[str]
    r"""Human-readable feature title."""
    type: NotRequired[str]
    r"""Feature type."""
    key: NotRequired[Key]
    r"""Feature key identifier."""


class ListProvidersResponseBody(BaseModel):
    r"""A feature supported by a media provider."""

    media_container: Annotated[
        Optional[ListProvidersMediaContainer], pydantic.Field(alias="MediaContainer")
    ] = None

    title: Optional[str] = None
    r"""Human-readable feature title."""

    type: Optional[str] = None
    r"""Feature type."""

    key: Optional[Key] = None
    r"""Feature key identifier."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["MediaContainer", "title", "type", "key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListProvidersResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    object: NotRequired[ListProvidersResponseBodyTypedDict]
    r"""OK"""


class ListProvidersResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    object: Optional[ListProvidersResponseBody] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["object"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ListProvidersMediaContainer.model_rebuild()
except NameError:
    pass
try:
    ListProvidersResponseBody.model_rebuild()
except NameError:
    pass
